### ISSUE TITLE
与cc预览站的连接问题

### ISSUE THREAD

**Issue by LanmeiCN** [Clipteam/clipcc-extension-store#1]
当https://codingclip.com/editor/dev/canary/ 被刷新或重新打开时，会出现以下两种情况：
1.本页不刷新，单击INSTALL无效
2.本页刷新，插件显示LOADING...
两种情况下均无法获得到实际插件安装情况。

**Comment by SimonShiki** [comment]
ClipCC与扩展站的连接方式是BroadcastChannel因此在编辑器不在频道上时扩展站无法获取当前扩展状态，不属于bug。
